### ISSUE TITLE
w2v_200.txt

### ISSUE THREAD

**Issue by wjczf123** [mark-xhchen/Conditional-ECPE#1]
Is the w2v_200.txt file the same as the w2v_200.txt used by Xia and Ding (Emotion-Cause Pair Extraction: A New Task to Emotion Analysis in Texts)?

**Comment by wjczf123** [comment]
I run main_lstm_agg.py and get 0.6841 F1.
I run main_lstm.py and get 0.7034 F1.
It seems that PAM doesnot achieve performance.
Is this the reason for the random seed?

**Comment by mark-xhchen** [comment]
Yes, the file is the same as the one in Xia and Ding's dataset.

**Comment by wjczf123** [comment]
OK. Thank you a lot.
